packages:
  - 'packages/*'
  - 'web'
  - 'api'
  - 'api-e2e'
  - 'libs/shared/*'
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  core-js-pure: false
  esbuild: true
  less: false
  nx: true
  prisma: true
  sharp: true
  unrs-resolver: false
